### ISSUE TITLE
Output format

### ISSUE THREAD

**Issue by umasstr** [FunctionLab/sei-manuscript#1]
I ran jobs with the sample BED and my own. In both cases, the output had a couple of issues:

1.  .tsv.gz extension. The file is not actually gzipped
2. no line breaks. the output is one line. Based on that line's length, every sequence's class was written to line1.

```$ awk '{print length}' b8c51416-c6dd-4447-8a0a-590b1e9f886c_feature_predictions.tsv.gz```

>65280

Sample output job ID: 129c88ae-da3a-4ea3-9aba-402763d52576

3. I'm not sure that the output headers (chrom, start, end etc.) correspond to anything, or what each tab-separated string is supposed to mean. Does the [documentation ](https://humanbase.readthedocs.io/en/latest/deepsea.html#output) correspond to an older version of this software? Some items (available reference genomes) don't match up as far as I can tell. 

![image](https://user-images.githubusercontent.com/44478133/178887679-f5d869c1-7773-47b4-9151-74489b229921.png)

4. If I replace tabs with line breaks, the sample BED output and my own BED output have the same number of lines. I'm not sure how to associate a line with my input sequences.

Apologies if I missed something in the documentation.

**Comment by aaronkw** [comment]
Hi, can you confirm that your file was downloaded from this url? 
```
http://s3-us-west-2.amazonaws.com/humanbase/deepsea/jobs/b8c51416-c6dd-4447-8a0a-590b1e9f886c/b8c51416-c6dd-4447-8a0a-590b1e9f886c_feature_predictions.tsv.gz
```

It should indeed be a gzip file: 
```bash
$ file b8c51416-c6dd-4447-8a0a-590b1e9f886c_feature_predictions.tsv.gz
b8c51416-c6dd-4447-8a0a-590b1e9f886c_feature_predictions.tsv.gz: Blocked GNU Zip Format (BGZF; gzip compatible), block length 10259
```

With 9K+ lines when unzipped:
```bash
$ wc -l b8c51416-c6dd-4447-8a0a-590b1e9f886c_feature_predictions.tsv
    9694 b8c51416-c6dd-4447-8a0a-590b1e9f886c_feature_predictions.tsv
```

**Comment by umasstr** [comment]
Sorry for the delayed reply. I see the issue: I clicked on the results link under Job details. It looks like the "Probability" link under "Feature level result files" ? Thanks!

Results:

https://s3-us-west-2.amazonaws.com/humanbase/deepsea/jobs/b8c51416-c6dd-4447-8a0a-590b1e9f886c/b8c51416-c6dd-4447-8a0a-590b1e9f886c.tar.gz

**Comment by umasstr** [comment]
Can you confirm that there should be >21K columns in the result document? This is the case with the link in your comment above. If so, could you point me to the documentation that helps interpret this?
